config/routes.rb
SampleApp::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  resources :products

  root 'static_pages#home'
  match '/goods',    to: 'static_pages#goods',    via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/catalogue',  to: 'products#show',         via: 'get'
  match '/kitchenspray',  to: 'products#kitchenspray',         via: 'get'
  match '/wipes',  to: 'products#wipes',         via: 'get'
  match '/floorcleaner',  to: 'products#floorcleaner',         via: 'get'

 

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :email, :password, :password_confirmation
  
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

before_filter :authorize, only: [:edit, :update]

  def show
    @cleaner = Product.find(1)
    @spray = Product.find(2)
    @wipes = Product.find(3)
  end

  def floorcleaner
    @product = Product.find(1)
      @stock = @product.stock
  end

  def kitchenspray
    @product = Product.find(2)
      @stock = @product.stock
  end	

  def wipes
    @product = Product.find(3)
      @stock = @product.stock
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to catalogue_path
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def goods
  end

	def contact
	end

	def login
	end
end	

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to catalogue_path
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Soviet Cleaners"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
  <div id="header">
    <div id="logo"><%= link_to image_tag('/assets/logo.png'), root_path %></div>
    <div id= "menu">Menu 
      <%= link_to "Home", root_path%>
      <%= link_to "Goods", goods_path %>
      <%= link_to "Contact", contact_path %>
    </div>
    <div id="welcomeMessage"></div>
  </div>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

  

app/views/products/floorcleaner.html.erb
<% provide(:title, 'Floor Cleaner') %>

<div id="content">
<p><% if current_user %>
	<h2>Soviet Cleaners Floor Polish</h2>
	<div id="feature"><img img border="0" src="assets/polish.png" alt="Soviet Cleaners Floor Cleaner"/>
	</div> 
    <p>
    	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit. in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>

  	<p class="yellow">
	<% if @stock == 0 %>
	Sorry we are out of stock
	<% else %>
	In stock! We have <%= @stock %> units left!
	<% end %>
	</p>

  <% else %>
   Please <%= link_to "login", login_path, :class => "nodec"%> or <%= link_to "register", signup_path, :class => "nodec"%> to view our Product Catalogue.
  <% end %>

<p/>
</div>

app/views/products/kitchenspray.html.erb
<% provide(:title, 'Kitchen Spray') %>

<div id="content">

<p><% if current_user %>
	<h2>Soviet Cleaners Kitchen Spray</h2>
	<div id="feature"><img img border="0" src="assets/spray.png" alt="Soviet Cleaners Kitchen Spray"/></div> 
  
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit. in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  	
  	<p class="yellow">
	<% if @stock == 0 %>
	Sorry we are out of stock.
	<% else %>
	In stock! We have <%= @stock %> units left!
	<% end %>
	</p>

  <% else %>
   Please <%= link_to "login", login_path, :class => "nodec"%> or <%= link_to "register", signup_path, :class => "nodec"%> to view our Product Catalogue.
  <% end %>

<p/>
</div>

app/views/products/show.html.erb
<% provide(:title, 'Product Catalogue') %>

<div id="bodyContent">

<p><% if current_user %>
	<h2>Product Catalogue</h1>
		<div id="table">
			<table table style= "font-family: bitterregular, 'gill sans', arial, helvetica, sans-serif;color: white;" border="1.5" width="50%">
			<tr>
				<th>Product</th>
				<th>Price</th>
			<tr>
				<td>
				<%= link_to @cleaner.product, @cleaner.url, :class => "nodec"%>	
				</td>
				<td>
				€<%= @spray.price %> 
			</td>
			</tr>

			<tr>
				<td>
				<%= link_to @spray.product, @spray.url, :class => "nodec"%>	
				</td>
				<td>
				€<%= @spray.price %> 
			</td>
			</tr> 
			 
			 <tr>
				<td>
				<%= link_to @wipes.product, @wipes.url, :class => "nodec"%>	
				</td>
				<td>
				€<%= @wipes.price %> 
			</td>
			</tr>

		</table>
		</div>
	<% else %>
	 Please <%= link_to "login", login_path, :class => "nodec"%> or <%= link_to "register", signup_path, :class => "nodec"%> to view our Product Catalogue.
	<% end %>


</div>

app/views/products/wipes.html.erb
<% provide(:title, 'Kitchen Wipes') %>

<div id="content">
<p><% if current_user %>
	<h2>Soviet Cleaners Kitchen Wipes</h2>
	<div id="feature"><img img border="0" src="assets/wipes.png" alt="Soviet Cleaners Kitchen Wipes"/></div> 

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit. in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    
    <p class="yellow">
	<% if @stock == 0 %>
	Sorry we are out of stock.
	<% else %>
	In stock! We have <%= @stock %> units left!
	<% end %>
	</p>

  <% else %>
   Please <%= link_to "login", login_path, :class => "nodec"%> or <%= link_to "register", signup_path, :class => "nodec"%> to view our Product Catalogue.
  <% end %>



<p/>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>

  <div id="right">
      The form contains <%= pluralize(@user.errors.count, "error") %>.  
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>

 
    <div id="form">
   
     <h2 style= "font-family: bitterregular, gill sans, arial, helvetica, sans-serif;color: white;">How To Get in Touch</h2>
       <div id="contact">  
        <form name="contactUs" action=""  onsubmit="return validate()" method="post">
            <p> 
             <input type = "hidden" name = "recipient" value = "info@cleanerfloors.ie"/> 
             <input type = "hidden" name = "subject" value = "feedback"/> 
             <input type = "hidden" name = "redirect" value = "index.html"/>  
            </p>  
            <p>
            <h3><strong>Drop us a Mail</strong></h3>         
            </p>
            
            <label>Your Name:<br/>
            <input name="name" type="text" value="" onkeyup="confirmation()"/>
            </label><div id = "nameError" class = "errorMessage"></div>
            <br/>
            
            <label>Your Phonenumber:<br/>
            <input name="telephone" type="text" value="" onkeyup="confirmation()"/>
            </label><div id = "phoneError" class = "errorMessage"></div>
            <br/>
            
            <label>Your Email Address:<br/>
            <input name="email" type="text"  value="" onkeyup="confirmation()"/>
            </label>
            <div id = "emailError" class = "errorMessage"></div>
            <div id = "emailFormatError" class = "errorMessage"></div> 
            <p>
            <label>Your Query:</label><br />
            <textarea name="query" rows="5" cols="30" onkeyup="confirmation()">Enter query here.</textarea>
            <div id = "queryError" class="errorMessage"></div>
            </p>
            <p>
            <br/>
            <input name="submit" type="submit" value="Send" />
            <input name="clear" type="reset" value="Clear"/>
            <div id = "confirmationMsg" class="errorMessage"></div>
            </p>
        </form>
       </div>
    
   <div id="address">       
    <p><h3><strong>Our Address</strong></h3></p>
    <p>74 Ballsbridge Ave.</p>
    <p>Ballsbridge</p>
    <p>Dublin 4</p>
    <p><strong>tel:</strong>084622887</p>
    <p><strong>fax:</strong>084622886</p>
    <p><strong>email:</strong><a href="mailto:info@sovietcleaners.ie" class="white">info@sovietcleaners.ie</a></p>
   </div> 

</div>

app/views/static_pages/goods.html.erb
<% provide(:title, 'Goods and Services') %>

<div id="bodyContent">

        <h1>Product Catalogue</h1>
       

        <div id="table"><table style= "font-family: bitterregular, 'gill sans', arial, helvetica, sans-serif;color: white;" border="1.5" width="50%" summary="Cleaner Floors Goods and Services">
            <thead>
                <tr>
                    <th>Service</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>House Cleaning</td>
                    <td>&euro;30 per hour</td>
                </tr>
                <tr>
                    <td>Corporate/Buisness Cleaning</td>
                    <td>&euro;50 per hour</td> 
                </tr>
                <tr>
                    <td>Soviet Cleaners Floor Cleaner&trade;</td>
                    <td>&euro;13 per litre</td>
                </tr>
            </tbody>
        </table>
    </div>
    
</div>
</div>    

app/views/static_pages/home.html.erb
<% provide(:title,) %>



  
  <div id="content">

   <h1 style= "font-family: bitterbold, 'gill sans', arial, helvetica, sans-serif;color: white;">
    Ireland's Leading Cleaning Company
  </h1>
  
  <div id="mpu"> <%= link_to image_tag('/assets/mpu.png'), catalogue_path %></div> 
  <h2 style= "font-family: bitterregular, 'gill sans', arial, helvetica, sans-serif;color: white;" >
    Leading the way since 2004
  </h2>
  
  <p style= "font-family: bitterregular, 'gill sans', arial, helvetica, sans-serif;color: white;" >
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
    magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit. in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </p>

  <p style= "font-family: bitterregular, 'gill sans', arial, helvetica, sans-serif;color: white;">
    If you wish to know more about what we do, please take a look at full break down of our
    <%= link_to "goods & services", goods_path, :class => "nodec"%>, or why not just drop us a mail on our
    <%= link_to "contact page", contact_path  , :class => "nodec"%>
  </p></br>
  
  <p>
  Want to see more? <%= link_to "Click here to register", signup_path, :class => "nodec"%> or <%= link_to "login", login_path, :class => "nodec"%> if you are a returning customer.
  </p>
</div>

app/views/users/new.html.erb
<% provide(:title,) %>

<div id="content">

<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

</div>